# Generated by Django 4.2.13 on 2024-06-11 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_cadastros', '0003_customuser_enterprise'),
        ('core_tenants', '0002_alter_tenant_schema_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='core_cadastros.enterprise'),
        ),
    ]
