# Generated by Django 3.2 on 2024-06-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
