# Generated by Django 4.2.13 on 2024-06-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_cadastros', '0002_alter_enterprise_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enterprise',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_cadastros.enterprise'),
        ),
    ]
