# Generated by Django 3.2 on 2024-06-13 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_tenants', '0003_alter_tenant_client'),
        ('core_cadastros', '0003_customuser_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_tenants.tenant'),
        ),
    ]
